//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Web.CodeGenerators.Mvc {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal MessageStrings() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.Web.CodeGenerators.Mvc.MessageStrings", typeof(MessageStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Controller Name is required.
        /// </summary>
        internal static string ControllerNameRequired {
            get {
                return ResourceManager.GetString("ControllerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Controller name is required for an Empty Controller.
        /// </summary>
        internal static string EmptyControllerNameRequired {
            get {
                return ResourceManager.GetString("EmptyControllerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The file {0} exists, use -f option to overwrite.
        /// </summary>
        internal static string FileExists_useforce {
            get {
                return ResourceManager.GetString("FileExists_useforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please provide a valid {0}.
        /// </summary>
        internal static string ProvideValidArgument {
            get {
                return ResourceManager.GetString("ProvideValidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There may be additional steps required for the generated code to work. Refer to &lt;forward-link&gt;.
        /// </summary>
        internal static string Scaffolding_additionalSteps {
            get {
                return ResourceManager.GetString("Scaffolding_additionalSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Scaffolding generated all the code but the new context created could be registered using dependency injection..
        /// </summary>
        internal static string ScaffoldingSuccessful_unregistered {
            get {
                return ResourceManager.GetString("ScaffoldingSuccessful_unregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The TemplateName cannot be empty.
        /// </summary>
        internal static string TemplateNameRequired {
            get {
                return ResourceManager.GetString("TemplateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A type with the name {0} does not exist.
        /// </summary>
        internal static string TypeDoesNotExist {
            get {
                return ResourceManager.GetString("TypeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Validation succeded but model type not set.
        /// </summary>
        internal static string ValidationSuccessfull_modelUnset {
            get {
                return ResourceManager.GetString("ValidationSuccessfull_modelUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The ViewName cannot be empty&quot;.
        /// </summary>
        internal static string ViewNameRequired {
            get {
                return ResourceManager.GetString("ViewNameRequired", resourceCulture);
            }
        }
    }
}
