// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Build.Locator;
using Microsoft.DotNet.Tools.Scaffold.Aspire.Helpers;
using Microsoft.Extensions.Logging;
using Xunit;

namespace Microsoft.DotNet.Tools.Scaffold.Tests.Aspire.Helpers;

public class AspireHelpersTests : IDisposable
{
    private readonly string _testProjectDirectory;
    private readonly string _testProjectPath;
    private readonly string _testObjDirectory;
    private readonly string _testDebugDirectory;
    private readonly TestLogger _testLogger;

    public AspireHelpersTests()
    {
        // Register MSBuild if not already registered
        if (!MSBuildLocator.IsRegistered)
        {
            MSBuildLocator.RegisterDefaults();
        }

        _testLogger = new TestLogger();
        _testProjectDirectory = Path.Combine(Path.GetTempPath(), "AspireHelpersTests", Guid.NewGuid().ToString());
        _testProjectPath = Path.Combine(_testProjectDirectory, "TestProject.AppHost.csproj");
        _testObjDirectory = Path.Combine(_testProjectDirectory, "obj");
        _testDebugDirectory = Path.Combine(_testObjDirectory, "Debug", "net9.0");

        Directory.CreateDirectory(_testProjectDirectory);
        Directory.CreateDirectory(_testDebugDirectory);

        // Create an Aspire AppHost project file
        File.WriteAllText(_testProjectPath, @"
<Project Sdk=""Microsoft.NET.Sdk"">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <IsAspireHost>true</IsAspireHost>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include=""Aspire.Hosting.AppHost"" Version=""9.0.0"" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include=""obj\Debug\net9.0\TestProject.AppHost.ProjectMetadata.g.cs"" />
  </ItemGroup>
</Project>");

        // Create a Program.cs file to make it a valid project
        File.WriteAllText(Path.Combine(_testProjectDirectory, "Program.cs"), @"
var builder = DistributedApplication.CreateBuilder(args);
builder.Build().Run();
");

        // Create the AppHost ProjectMetadata file that Roslyn will discover
        string appHostMetadata = @"
namespace Projects
{
    public class TestProject
    {}
}";
        File.WriteAllText(Path.Combine(_testDebugDirectory, "TestProject.AppHost.ProjectMetadata.g.cs"), appHostMetadata);
    }

    public void Dispose()
    {
        if (Directory.Exists(_testProjectDirectory))
        {
            try
            {
                Directory.Delete(_testProjectDirectory, true);
            }
            catch
            {
                // Ignore cleanup errors
            }
        }
    }


    private class TestLogger : ILogger
    {
        public List<string> ErrorMessages { get; } = new();
        public List<string> InfoMessages { get; } = new();

        public IDisposable? BeginScope<TState>(TState state) where TState : notnull => null;

        public bool IsEnabled(LogLevel logLevel) => true;

        public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception? exception, Func<TState, Exception?, string> formatter)
        {
            string message = formatter(state, exception);
            if (logLevel == LogLevel.Error)
            {
                ErrorMessages.Add(message);
            }
            else if (logLevel == LogLevel.Information)
            {
                InfoMessages.Add(message);
            }
        }
    }

    [Fact]
    public async Task GetAutoGeneratedProjectNamesAsync_NoProjectMetadataFile_ReturnsEmptyDictionary()
    {
        // Arrange - no ProjectMetadata.g.cs files created in the obj directory

        // Act
        Dictionary<string, string> result = await AspireHelpers.GetAutoGeneratedProjectNamesAsync(_testProjectPath, _testLogger);

        // Assert
        Assert.NotNull(result);
        Assert.Empty(result);
    }

    [Fact]
    public async Task GetAutoGeneratedProjectNamesAsync_WithSingleProjectMetadataFile_ReturnsProjectName()
    {
        // Arrange
        string projectMetadataContent = @"
namespace Projects
{
    public class ApiService
    {
        public string ProjectPath => ""/path/to/ApiService.csproj"";
    }
}";
        string metadataFilePath = Path.Combine(_testDebugDirectory, "ApiService.ProjectMetadata.g.cs");
        File.WriteAllText(metadataFilePath, projectMetadataContent);

        // Act
        Dictionary<string, string> result = await AspireHelpers.GetAutoGeneratedProjectNamesAsync(_testProjectPath, _testLogger);

        // Assert
        Assert.NotNull(result);
        Assert.Single(result);
        Assert.True(result.ContainsKey("/path/to/ApiService.csproj"));
        Assert.Equal("Projects.ApiService", result["/path/to/ApiService.csproj"]);
    }

    [Fact]
    public async Task GetAutoGeneratedProjectNamesAsync_MultipleProjectMetadataFiles_ReturnsAllProjectNames()
    {
        // Arrange
        string apiServiceMetadata = @"
namespace Projects
{
    public class ApiService
    {
        public string ProjectPath => ""/path/to/ApiService.csproj"";
    }
}";
        string webAppMetadata = @"
namespace Projects
{
    public class WebApp
    {
        public string ProjectPath => ""/path/to/WebApp.csproj"";
    }
}";

        File.WriteAllText(Path.Combine(_testDebugDirectory, "ApiService.ProjectMetadata.g.cs"), apiServiceMetadata);
        File.WriteAllText(Path.Combine(_testDebugDirectory, "WebApp.ProjectMetadata.g.cs"), webAppMetadata);

        // Act
        Dictionary<string, string> result = await AspireHelpers.GetAutoGeneratedProjectNamesAsync(_testProjectPath, _testLogger);

        // Assert
        Assert.NotNull(result);
        Assert.Equal(2, result.Count);
        Assert.True(result.ContainsKey("/path/to/ApiService.csproj"));
        Assert.Equal("Projects.ApiService", result["/path/to/ApiService.csproj"]);
        Assert.True(result.ContainsKey("/path/to/WebApp.csproj"));
        Assert.Equal("Projects.WebApp", result["/path/to/WebApp.csproj"]);
    }

    [Fact]
    public async Task GetAutoGeneratedProjectNamesAsync_ProjectMetadataWithoutProjectPath_DoesNotIncludeInResult()
    {
        // Arrange
        string metadataWithoutProjectPath = @"
namespace Projects
{
    public class InvalidProject
    {
        public string SomeOtherProperty => ""value"";
    }
}";
        string validMetadata = @"
namespace Projects
{
    public class ValidProject
    {
        public string ProjectPath => ""/path/to/ValidProject.csproj"";
    }
}";

        File.WriteAllText(Path.Combine(_testDebugDirectory, "InvalidProject.ProjectMetadata.g.cs"), metadataWithoutProjectPath);
        File.WriteAllText(Path.Combine(_testDebugDirectory, "ValidProject.ProjectMetadata.g.cs"), validMetadata);

        // Act
        Dictionary<string, string> result = await AspireHelpers.GetAutoGeneratedProjectNamesAsync(_testProjectPath, _testLogger);

        // Assert
        Assert.NotNull(result);
        Assert.Single(result);
        Assert.DoesNotContain(result, kvp => kvp.Value.Contains("InvalidProject"));
        Assert.True(result.ContainsKey("/path/to/ValidProject.csproj"));
        Assert.Equal("Projects.ValidProject", result["/path/to/ValidProject.csproj"]);
    }

    [Fact]
    public async Task GetAutoGeneratedProjectNamesAsync_ClassNotInProjectsNamespace_DoesNotIncludeInResult()
    {
        // Arrange
        string wrongNamespaceMetadata = @"
namespace WrongNamespace
{
    public class SomeProject
    {
        public string ProjectPath => ""/path/to/SomeProject.csproj"";
    }
}";
        string correctNamespaceMetadata = @"
namespace Projects
{
    public class CorrectProject
    {
        public string ProjectPath => ""/path/to/CorrectProject.csproj"";
    }
}";

        File.WriteAllText(Path.Combine(_testDebugDirectory, "SomeProject.ProjectMetadata.g.cs"), wrongNamespaceMetadata);
        File.WriteAllText(Path.Combine(_testDebugDirectory, "CorrectProject.ProjectMetadata.g.cs"), correctNamespaceMetadata);

        // Act
        Dictionary<string, string> result = await AspireHelpers.GetAutoGeneratedProjectNamesAsync(_testProjectPath, _testLogger);

        // Assert
        Assert.NotNull(result);
        Assert.Single(result);
        Assert.DoesNotContain(result, kvp => kvp.Key == "/path/to/SomeProject.csproj");
        Assert.True(result.ContainsKey("/path/to/CorrectProject.csproj"));
        Assert.Equal("Projects.CorrectProject", result["/path/to/CorrectProject.csproj"]);
    }

    [Fact]
    public async Task GetAutoGeneratedProjectNamesAsync_ProjectMetadataInSubdirectory_FindsAllFiles()
    {
        // Arrange
        string subDirectory = Path.Combine(_testDebugDirectory, "subdirectory");
        Directory.CreateDirectory(subDirectory);

        string rootLevelMetadata = @"
namespace Projects
{
    public class RootProject
    {
        public string ProjectPath => ""/path/to/RootProject.csproj"";
    }
}";
        string subDirectoryMetadata = @"
namespace Projects
{
    public class SubProject
    {
        public string ProjectPath => ""/path/to/SubProject.csproj"";
    }
}";

        File.WriteAllText(Path.Combine(_testDebugDirectory, "RootProject.ProjectMetadata.g.cs"), rootLevelMetadata);
        File.WriteAllText(Path.Combine(subDirectory, "SubProject.ProjectMetadata.g.cs"), subDirectoryMetadata);

        // Act
        Dictionary<string, string> result = await AspireHelpers.GetAutoGeneratedProjectNamesAsync(_testProjectPath, _testLogger);

        // Assert
        Assert.NotNull(result);
        Assert.Equal(2, result.Count);
        Assert.True(result.ContainsKey("/path/to/RootProject.csproj"));
        Assert.Equal("Projects.RootProject", result["/path/to/RootProject.csproj"]);
        Assert.True(result.ContainsKey("/path/to/SubProject.csproj"));
        Assert.Equal("Projects.SubProject", result["/path/to/SubProject.csproj"]);
    }

    [Fact]
    public async Task GetAutoGeneratedProjectNamesAsync_DuplicateProjectPaths_TakesFirstOccurrence()
    {
        // Arrange
        string firstMetadata = @"
namespace Projects
{
    public class FirstProject
    {
        public string ProjectPath => ""/path/to/DuplicateProject.csproj"";
    }
}";
        string secondMetadata = @"
namespace Projects
{
    public class SecondProject
    {
        public string ProjectPath => ""/path/to/DuplicateProject.csproj"";
    }
}";

        File.WriteAllText(Path.Combine(_testDebugDirectory, "FirstProject.ProjectMetadata.g.cs"), firstMetadata);
        File.WriteAllText(Path.Combine(_testDebugDirectory, "SecondProject.ProjectMetadata.g.cs"), secondMetadata);

        // Act
        Dictionary<string, string> result = await AspireHelpers.GetAutoGeneratedProjectNamesAsync(_testProjectPath, _testLogger);

        // Assert
        Assert.NotNull(result);
        Assert.Single(result);
        Assert.True(result.ContainsKey("/path/to/DuplicateProject.csproj"));
        // TryAdd will keep the first occurrence
        string projectValue = result["/path/to/DuplicateProject.csproj"];
        Assert.True(projectValue == "Projects.FirstProject" || projectValue == "Projects.SecondProject");
    }

    [Fact]
    public async Task GetAutoGeneratedProjectNamesAsync_EmptyProjectPath_DoesNotIncludeInResult()
    {
        // Arrange
        string emptyProjectPathMetadata = @"
namespace Projects
{
    public class EmptyPathProject
    {
        public string ProjectPath => """";
    }
}";
        string validMetadata = @"
namespace Projects
{
    public class ValidProject
    {
        public string ProjectPath => ""/path/to/ValidProject.csproj"";
    }
}";

        File.WriteAllText(Path.Combine(_testDebugDirectory, "EmptyPathProject.ProjectMetadata.g.cs"), emptyProjectPathMetadata);
        File.WriteAllText(Path.Combine(_testDebugDirectory, "ValidProject.ProjectMetadata.g.cs"), validMetadata);

        // Act
        Dictionary<string, string> result = await AspireHelpers.GetAutoGeneratedProjectNamesAsync(_testProjectPath, _testLogger);

        // Assert
        Assert.NotNull(result);
        Assert.Single(result);
        Assert.DoesNotContain(result, kvp => string.IsNullOrEmpty(kvp.Key));
        Assert.True(result.ContainsKey("/path/to/ValidProject.csproj"));
        Assert.Equal("Projects.ValidProject", result["/path/to/ValidProject.csproj"]);
    }

    [Fact]
    public async Task GetAutoGeneratedProjectNamesAsync_ReturnsFullyQualifiedClassName()
    {
        // Arrange
        string projectMetadata = @"
namespace Projects
{
    public class MyCustomService
    {
        public string ProjectPath => ""/path/to/MyCustomService.csproj"";
    }
}";

        File.WriteAllText(Path.Combine(_testDebugDirectory, "MyCustomService.ProjectMetadata.g.cs"), projectMetadata);

        // Act
        Dictionary<string, string> result = await AspireHelpers.GetAutoGeneratedProjectNamesAsync(_testProjectPath, _testLogger);

        // Assert
        Assert.NotNull(result);
        Assert.Single(result);
        Assert.True(result.ContainsKey("/path/to/MyCustomService.csproj"));
        Assert.Equal("Projects.MyCustomService", result["/path/to/MyCustomService.csproj"]);
        Assert.StartsWith("Projects.", result.Values.First());
    }
}

