//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.Tools.Scaffold.AspNet.Templates.net10.Files {
    using System;


    internal partial class _LoginPartial : _LoginPartialBase {

        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;


        private Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel _ModelField;

        public Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel Model {
            get {
                return this._ModelField;
            }
        }


        public global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host {
            get {
                return this.hostValue;
            }
            set {
                this.hostValue = value;
            }
        }

        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            this.Write("@using Microsoft.AspNetCore.Identity\r\n@using ");
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.UserClassNamespace ));
            this.Write("\r\n@inject SignInManager<");
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.UserClassName ));
            this.Write("> SignInManager\r\n@inject UserManager<");
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.UserClassName ));
            this.Write(@"> UserManager

<ul class=""navbar-nav"">
@if (SignInManager.IsSignedIn(User))
{
    <li class=""nav-item"">
        <a class=""nav-link text-dark"" asp-area=""Identity"" asp-page=""/Account/Manage/Index"" title=""Manage"">Hello @User.Identity?.Name!</a>
    </li>
    <li class=""nav-item"">
        <form class=""form-inline"" asp-area=""Identity"" asp-page=""/Account/Logout"" asp-route-returnUrl=""");
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.IsRazorPages ? "@Url.Page(\"/Index\", new { area = \"\" })" : "@Url.Action(\"Index\", \"Home\", new { area = \"\" })" ));
            this.Write(@""">
            <button type=""submit"" class=""nav-link btn btn-link text-dark"">Logout</button>
        </form>
    </li>
}
else
{
    <li class=""nav-item"">
        <a class=""nav-link text-dark"" asp-area=""Identity"" asp-page=""/Account/Register"">Register</a>
    </li>
    <li class=""nav-item"">
        <a class=""nav-link text-dark"" asp-area=""Identity"" asp-page=""/Account/Login"">Login</a>
    </li>
}
</ul>
");
            return this.GenerationEnvironment.ToString();
        }

        public virtual void Initialize() {
            if ((this.Errors.HasErrors == false)) {
                bool _ModelAcquired = false;
                if (((this.Session != null)
                            && this.Session.ContainsKey("Model"))) {
                    object data = this.Session["Model"];
                    if (typeof(Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel).IsAssignableFrom(data.GetType())) {
                        this._ModelField = ((Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel)(data));
                        _ModelAcquired = true;
                    }
                    else {
                        this.Error(("The type \'Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel\' of the par" +
                                "ameter \'Model\' did not match the type passed to the template"));
                    }
                }
                if (((_ModelAcquired == false)
                            && (this.Host != null))) {
                    string data = ((global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost)(this.Host)).ResolveParameterValue(null, null, "Model");
                    if ((data != null)) {
                        global::System.ComponentModel.TypeConverter dataTypeConverter = System.ComponentModel.TypeDescriptor.GetConverter(typeof(Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel));
                        if (((dataTypeConverter != null)
                                    && dataTypeConverter.CanConvertFrom(typeof(string)))) {
                            this._ModelField = ((Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel)(dataTypeConverter.ConvertFromString(data)));
                        }
                        else {
                            this.Error(("The host parameter \'Model\' could not be converted to the type \'System.CodeDom.Cod" +
                                    "eTypeReference\' specified in the template"));
                        }
                    }
                }
            }

        }
    }

    public class _LoginPartialBase {

        private global::System.Text.StringBuilder builder;

        private global::System.Collections.Generic.IDictionary<string, object> session;

        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;

        private string currentIndent = string.Empty;

        private global::System.Collections.Generic.Stack<int> indents;

        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();

        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }

        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }

        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }

        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }

        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }

        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }

        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }

        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }

        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }

        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }

        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }

        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }

        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }

        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }

        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }

        public class ToStringInstanceHelper {

            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;

            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }

            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
