// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.DotNet.Tools.Scaffold.AspNet.Templates.BlazorIdentity.Pages.Manage
{
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class TwoFactorAuthentication : TwoFactorAuthenticationBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("@page \"/Account/Manage/TwoFactorAuthentication\"\r\n\r\n@using Microsoft.AspNetCore.Ht" +
                    "tp.Features\r\n@using Microsoft.AspNetCore.Identity\r\n");

if (!string.IsNullOrEmpty(Model.DbContextNamespace))
{

            this.Write("@using ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DbContextNamespace));
            this.Write("\r\n");
} 
            this.Write("\r\n@inject UserManager<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write("> UserManager\r\n@inject SignInManager<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write("> SignInManager\r\n@inject IdentityRedirectManager RedirectManager\r\n\r\n<PageTitle>Tw" +
                    "o-factor authentication (2FA)</PageTitle>\r\n\r\n<StatusMessage />\r\n<h3>Two-factor a" +
                    "uthentication (2FA)</h3>\r\n@if (canTrack)\r\n{\r\n    if (is2faEnabled)\r\n    {\r\n     " +
                    "   if (recoveryCodesLeft == 0)\r\n        {\r\n            <div class=\"alert alert-d" +
                    "anger\">\r\n                <strong>You have no recovery codes left.</strong>\r\n    " +
                    "            <p>You must <a href=\"Account/Manage/GenerateRecoveryCodes\">generate " +
                    "a new set of recovery codes</a> before you can log in with a recovery code.</p>\r" +
                    "\n            </div>\r\n        }\r\n        else if (recoveryCodesLeft == 1)\r\n      " +
                    "  {\r\n            <div class=\"alert alert-danger\">\r\n                <strong>You h" +
                    "ave 1 recovery code left.</strong>\r\n                <p>You can <a href=\"Account/" +
                    "Manage/GenerateRecoveryCodes\">generate a new set of recovery codes</a>.</p>\r\n   " +
                    "         </div>\r\n        }\r\n        else if (recoveryCodesLeft <= 3)\r\n        {\r" +
                    "\n            <div class=\"alert alert-warning\">\r\n                <strong>You have" +
                    " @recoveryCodesLeft recovery codes left.</strong>\r\n                <p>You should" +
                    " <a href=\"Account/Manage/GenerateRecoveryCodes\">generate a new set of recovery c" +
                    "odes</a>.</p>\r\n            </div>\r\n        }\r\n\r\n        if (isMachineRemembered)" +
                    "\r\n        {\r\n            <form style=\"display: inline-block\" @formname=\"forget-b" +
                    "rowser\" @onsubmit=\"OnSubmitForgetBrowserAsync\" method=\"post\">\r\n                <" +
                    "AntiforgeryToken />\r\n                <button type=\"submit\" class=\"btn btn-primar" +
                    "y\">Forget this browser</button>\r\n            </form>\r\n        }\r\n\r\n        <a hr" +
                    "ef=\"Account/Manage/Disable2fa\" class=\"btn btn-primary\">Disable 2FA</a>\r\n        " +
                    "<a href=\"Account/Manage/GenerateRecoveryCodes\" class=\"btn btn-primary\">Reset rec" +
                    "overy codes</a>\r\n    }\r\n\r\n    <h4>Authenticator app</h4>\r\n    @if (!hasAuthentic" +
                    "ator)\r\n    {\r\n        <a href=\"Account/Manage/EnableAuthenticator\" class=\"btn bt" +
                    "n-primary\">Add authenticator app</a>\r\n    }\r\n    else\r\n    {\r\n        <a href=\"A" +
                    "ccount/Manage/EnableAuthenticator\" class=\"btn btn-primary\">Set up authenticator " +
                    "app</a>\r\n        <a href=\"Account/Manage/ResetAuthenticator\" class=\"btn btn-prim" +
                    "ary\">Reset authenticator app</a>\r\n    }\r\n}\r\nelse\r\n{\r\n    <div class=\"alert alert" +
                    "-danger\">\r\n        <strong>Privacy and cookie policy have not been accepted.</st" +
                    "rong>\r\n        <p>You must accept the policy before you can enable two factor au" +
                    "thentication.</p>\r\n    </div>\r\n}\r\n\r\n@code {\r\n    private bool canTrack;\r\n    pri" +
                    "vate bool hasAuthenticator;\r\n    private int recoveryCodesLeft;\r\n    private boo" +
                    "l is2faEnabled;\r\n    private bool isMachineRemembered;\r\n\r\n    [CascadingParamete" +
                    "r]\r\n    private HttpContext HttpContext { get; set; } = default!;\r\n\r\n    protect" +
                    "ed override async Task OnInitializedAsync()\r\n    {\r\n        var user = await Use" +
                    "rManager.GetUserAsync(HttpContext.User);\r\n        if (user is null)\r\n        {\r\n" +
                    "            RedirectManager.RedirectToInvalidUser(UserManager, HttpContext);\r\n  " +
                    "          return;\r\n        }\r\n\r\n        canTrack = HttpContext.Features.Get<ITra" +
                    "ckingConsentFeature>()?.CanTrack ?? true;\r\n        hasAuthenticator = await User" +
                    "Manager.GetAuthenticatorKeyAsync(user) is not null;\r\n        is2faEnabled = awai" +
                    "t UserManager.GetTwoFactorEnabledAsync(user);\r\n        isMachineRemembered = awa" +
                    "it SignInManager.IsTwoFactorClientRememberedAsync(user);\r\n        recoveryCodesL" +
                    "eft = await UserManager.CountRecoveryCodesAsync(user);\r\n    }\r\n\r\n    private asy" +
                    "nc Task OnSubmitForgetBrowserAsync()\r\n    {\r\n        await SignInManager.ForgetT" +
                    "woFactorClientAsync();\r\n\r\n        RedirectManager.RedirectToCurrentPageWithStatu" +
                    "s(\r\n            \"The current browser has been forgotten. When you login again fr" +
                    "om this browser you will be prompted for your 2fa code.\",\r\n            HttpConte" +
                    "xt);\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        /// <summary>
        /// The current host for the text templating engine
        /// </summary>
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }

private global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel _ModelField;

/// <summary>
/// Access the Model parameter of the template.
/// </summary>
private global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel Model
{
    get
    {
        return this._ModelField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ModelValueAcquired = false;
if (this.Session.ContainsKey("Model"))
{
    this._ModelField = ((global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel)(this.Session["Model"]));
    ModelValueAcquired = true;
}
if ((ModelValueAcquired == false))
{
    string parameterValue = this.Host.ResolveParameterValue("Property", "PropertyDirectiveProcessor", "Model");
    if ((string.IsNullOrEmpty(parameterValue) == false))
    {
        global::System.ComponentModel.TypeConverter tc = global::System.ComponentModel.TypeDescriptor.GetConverter(typeof(global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel));
        if (((tc != null) 
                    && tc.CanConvertFrom(typeof(string))))
        {
            this._ModelField = ((global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel)(tc.ConvertFrom(parameterValue)));
            ModelValueAcquired = true;
        }
        else
        {
            this.Error("The type \'Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel\' of the par" +
                    "ameter \'Model\' did not match the type of the data passed to the template.");
        }
    }
}
if ((ModelValueAcquired == false))
{
    object data = global::Microsoft.DotNet.Scaffolding.TextTemplating.CallContext.LogicalGetData("Model");
    if ((data != null))
    {
        this._ModelField = ((global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel)(data));
    }
}


    }
}


    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class TwoFactorAuthenticationBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
