// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Reflection;

namespace Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore
{
    public interface IPropertyMetadata
    {
        bool IsAutoGenerated { get; set; }
        bool IsEnum { get; set; }
        bool IsEnumFlags { get; set; }
        bool IsForeignKey { get; set; }
        bool IsPrimaryKey { get; set; }
        bool IsReadOnly { get; set; }
        string PropertyName { get; set; }
        bool Scaffold { get; set; }
        string ShortTypeName { get; set; }
        string TypeName { get; set; }
        bool IsMultilineText { get; set; }

        PropertyInfo PropertyInfo { get; set; }
    }
}
