// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.DotNet.Tools.Scaffold.AspNet.Templates.net11.BlazorIdentity.Pages
{
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using System;

    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class Login : LoginBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("@page \"/Account/Login\"\r\n\r\n@using System.ComponentModel.DataAnnotations\r\n@using Mi" +
                    "crosoft.AspNetCore.Authentication\r\n@using Microsoft.AspNetCore.Identity\r\n");

if (!string.IsNullOrEmpty(Model.DbContextNamespace))
{

            this.Write("@using ");
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.DbContextNamespace ));
            this.Write("\r\n");
}
            this.Write("\r\n@inject UserManager<");
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.UserClassName ));
            this.Write("> UserManager\r\n@inject SignInManager<");
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.UserClassName ));
            this.Write("> SignInManager\r\n@inject ILogger<Login> Logger\r\n@inject NavigationManager Navigat" +
                    "ionManager\r\n@inject IdentityRedirectManager RedirectManager\r\n\r\n<PageTitle>Log in" +
                    "</PageTitle>\r\n\r\n<h1>Log in</h1>\r\n<div class=\"row\">\r\n    <div class=\"col-lg-6\">\r\n" +
                    "        <section>\r\n            <StatusMessage Message=\"@errorMessage\" />\r\n      " +
                    "      <EditForm EditContext=\"editContext\" method=\"post\" OnSubmit=\"LoginUser\" For" +
                    "mName=\"login\">\r\n                <DataAnnotationsValidator />\r\n                <h" +
                    "2>Use a local account to log in.</h2>\r\n                <hr />\r\n                <div role=\"alert\" aria-atomic=\"true\">\r\n                    <ValidationSummary class=\"text-danger\" />\r\n                </div>\r\n" +
                    "                <div clas" +
                    "s=\"form-floating mb-3\">\r\n                    <InputText @bind-Value=\"Input.Email" +
                    "\" id=\"Input.Email\" class=\"form-control\" autocomplete=\"username webauthn\" aria-re" +
                    "quired=\"true\" placeholder=\"name@example.com\" />\r\n                    <label for=" +
                    "\"Input.Email\" class=\"form-label\">\r\n                        <DisplayName For=\"() " +
                    "=> Input.Email\" />\r\n                    </label>\r\n                    <Validatio" +
                    "nMessage For=\"() => Input.Email\" class=\"text-danger\" />\r\n                </div>\r" +
                    "\n                <div class=\"form-floating mb-3\">\r\n                <InputText ty" +
                    "pe=\"password\" @bind-Value=\"Input.Password\" id=\"Input.Password\" class=\"form-contr" +
                    "ol\" autocomplete=\"current-password\" aria-required=\"true\" placeholder=\"password\" " +
                    "/>\r\n                <label for=\"Input.Password\" class=\"form-label\">\r\n           " +
                    "         <DisplayName For=\"() => Input.Password\" />\r\n                </label>\r\n " +
                    "               <ValidationMessage For=\"() => Input.Password\" class=\"text-danger\"" +
                    " />\r\n                </div>\r\n                <div class=\"checkbox mb-3\">\r\n      " +
                    "              <label class=\"form-label\">\r\n                        <InputCheckbox" +
                    " @bind-Value=\"Input.RememberMe\" class=\"darker-border-checkbox form-check-input\" " +
                    "/>\r\n                        Remember me\r\n                    </label>\r\n         " +
                    "       </div>\r\n                <div>\r\n                    <button type=\"submit\" " +
                    "class=\"w-100 btn btn-lg btn-primary\">Log in</button>\r\n                </div>\r\n  " +
                    "              <hr />\r\n                <div class=\"d-flex flex-column\">\r\n        " +
                    "            <span class=\"text-secondary mx-auto mt-2\">OR</span>\r\n               " +
                    "     <PasskeySubmit Operation=\"PasskeyOperation.Request\" Name=\"Input.Passkey\" Em" +
                    "ailName=\"Input.Email\" class=\"btn btn-link mx-auto\">Log in with a passkey</Passke" +
                    "ySubmit>\r\n                </div>\r\n                <hr />\r\n                <div>\r" +
                    "\n                    <p>\r\n                        <a href=\"Account/ForgotPasswor" +
                    "d\">Forgot your password?</a>\r\n                    </p>\r\n                    <p>\r" +
                    "\n                        <a href=\"@(NavigationManager.GetUriWithQueryParameters(" +
                    "\"Account/Register\", new Dictionary<string, object?> { [\"ReturnUrl\"] = ReturnUrl " +
                    "}))\">Register as a new user</a>\r\n                    </p>\r\n                    <" +
                    "p>\r\n                        <a href=\"Account/ResendEmailConfirmation\">Resend ema" +
                    "il confirmation</a>\r\n                    </p>\r\n                </div>\r\n         " +
                    "   </EditForm>\r\n        </section>\r\n    </div>\r\n    <div class=\"col-lg-4 col-lg-" +
                    "offset-2\">\r\n        <section>\r\n            <h3>Use another service to log in.</h" +
                    "3>\r\n            <hr />\r\n            <ExternalLoginPicker />\r\n        </section>\r" +
                    "\n    </div>\r\n</div>\r\n\r\n@code {\r\n    private string? errorMessage;\r\n    private E" +
                    "ditContext editContext = default!;\r\n\r\n    [CascadingParameter]\r\n    private Http" +
                    "Context HttpContext { get; set; } = default!;\r\n\r\n    [SupplyParameterFromTempDat" +
                    "a(Name = IdentityRedirectManager.StatusMessageKey)]\r\n    private string? Identit" +
                    "yStatusMessage { get; set; }\r\n\r\n    [SupplyParameterFromForm]\r\n    private Input" +
                    "Model Input { get; set; } = default!;\r\n\r\n    [SupplyParameterFromQuery]\r\n    pri" +
                    "vate string? ReturnUrl { get; set; }\r\n\r\n    protected override async Task OnInit" +
                    "ializedAsync()\r\n    {\r\n        errorMessage = IdentityStatusMessage;\r\n        Id" +
                    "entityStatusMessage = null;\r\n        Input ??= new();\r\n\r\n        editContext = n" +
                    "ew EditContext(Input);\r\n\r\n        if (HttpMethods.IsGet(HttpContext.Request.Meth" +
                    "od))\r\n        {\r\n            // Clear the existing external cookie to ensure a c" +
                    "lean login process\r\n            await HttpContext.SignOutAsync(IdentityConstants" +
                    ".ExternalScheme);\r\n        }\r\n    }\r\n\r\n    public async Task LoginUser()\r\n    {\r" +
                    "\n        if (!string.IsNullOrEmpty(Input.Passkey?.Error))\r\n        {\r\n          " +
                    "  errorMessage = $\"Error: {Input.Passkey.Error}\";\r\n            return;\r\n        " +
                    "}\r\n\r\n        SignInResult result;\r\n        if (!string.IsNullOrEmpty(Input.Passk" +
                    "ey?.CredentialJson))\r\n        {\r\n            // When performing passkey sign-in," +
                    " don\'t perform form validation.\r\n            result = await SignInManager.Passke" +
                    "ySignInAsync(Input.Passkey.CredentialJson);\r\n        }\r\n        else\r\n        {\r" +
                    "\n            // If doing a password sign-in, validate the form.\r\n            if " +
                    "(!await editContext.ValidateAsync())\r\n            {\r\n                return;\r\n  " +
                    "          }\r\n\r\n            // This doesn\'t count login failures towards account " +
                    "lockout\r\n            // To enable password failures to trigger account lockout, " +
                    "set lockoutOnFailure: true\r\n            result = await SignInManager.PasswordSig" +
                    "nInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false)" +
                    ";\r\n        }\r\n\r\n        if (result.Succeeded)\r\n        {\r\n            Logger.Log" +
                    "Information(\"User logged in.\");\r\n            RedirectManager.RedirectTo(ReturnUr" +
                    "l);\r\n        }\r\n        else if (result.RequiresTwoFactor)\r\n        {\r\n         " +
                    "   RedirectManager.RedirectTo(\r\n                \"Account/LoginWith2fa\",\r\n       " +
                    "         new() { [\"returnUrl\"] = ReturnUrl, [\"rememberMe\"] = Input.RememberMe })" +
                    ";\r\n        }\r\n        else if (result.IsLockedOut)\r\n        {\r\n            Logge" +
                    "r.LogWarning(\"User account locked out.\");\r\n            RedirectManager.RedirectT" +
                    "o(\"Account/Lockout\");\r\n        }\r\n        else\r\n        {\r\n            errorMess" +
                    "age = \"Error: Invalid login attempt.\";\r\n        }\r\n    }\r\n\r\n    private sealed c" +
                    "lass InputModel\r\n    {\r\n        [Required]\r\n        [EmailAddress]\r\n        [Dis" +
                    "play(Name = \"Email\")]\r\n        public string Email { get; set; } = \"\";\r\n\r\n      " +
                    "  [Required]\r\n        [DataType(DataType.Password)]\r\n        [Display(Name = \"Pa" +
                    "ssword\")]\r\n        public string Password { get; set; } = \"\";\r\n\r\n        [Displa" +
                    "y(Name = \"Remember me?\")]\r\n        public bool RememberMe { get; set; }\r\n\r\n     " +
                    "   public PasskeyInputModel? Passkey { get; set; }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }

        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        /// <summary>
        /// The current host for the text templating engine
        /// </summary>
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }

private global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel _ModelField;

/// <summary>
/// Access the Model parameter of the template.
/// </summary>
private global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel Model
{
    get
    {
        return this._ModelField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ModelValueAcquired = false;
if (this.Session.ContainsKey("Model"))
{
    this._ModelField = ((global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel)(this.Session["Model"]));
    ModelValueAcquired = true;
}
if ((ModelValueAcquired == false))
{
    string parameterValue = this.Host.ResolveParameterValue("Property", "PropertyDirectiveProcessor", "Model");
    if ((string.IsNullOrEmpty(parameterValue) == false))
    {
        global::System.ComponentModel.TypeConverter tc = global::System.ComponentModel.TypeDescriptor.GetConverter(typeof(global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel));
        if (((tc != null)
                    && tc.CanConvertFrom(typeof(string))))
        {
            this._ModelField = ((global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel)(tc.ConvertFrom(parameterValue)));
            ModelValueAcquired = true;
        }
        else
        {
            this.Error("The type \'Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel\' of the par" +
                    "ameter \'Model\' did not match the type of the data passed to the template.");
        }
    }
}
if ((ModelValueAcquired == false))
{
    object data = global::Microsoft.DotNet.Scaffolding.TextTemplating.CallContext.LogicalGetData("Model");
    if ((data != null))
    {
        this._ModelField = ((global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel)(data));
    }
}


    }
}


    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class LoginBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0)
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}