//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Web.CodeGeneration.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.Web.CodeGeneration.Tools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add Microsoft.VisualStudio.Web.CodeGeneration.Design package to the project as a NuGet package reference..
        /// </summary>
        internal static string AddDesignPackage {
            get {
                return ResourceManager.GetString("AddDesignPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code generation for Asp.net Core.
        /// </summary>
        internal static string AppDesc {
            get {
                return ResourceManager.GetString("AppDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available frameworks in project: {0}.
        /// </summary>
        internal static string AvailableFrameworks {
            get {
                return ResourceManager.GetString("AvailableFrameworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available generators:.
        /// </summary>
        internal static string AvailableGeneratorsHeader {
            get {
                return ResourceManager.GetString("AvailableGeneratorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Failed..
        /// </summary>
        internal static string BuildFailed {
            get {
                return ResourceManager.GetString("BuildFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building project ....
        /// </summary>
        internal static string BuildingProject {
            get {
                return ResourceManager.GetString("BuildingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration for the project (Possible values: Debug/ Release).
        /// </summary>
        internal static string ConfigurationOptionDesc {
            get {
                return ResourceManager.GetString("ConfigurationOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to port {0}..
        /// </summary>
        internal static string ConnectToServerError {
            get {
                return ResourceManager.GetString("ConnectToServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see more information, enable tracing by setting environment variable &apos;codegen_trace&apos; = 1..
        /// </summary>
        internal static string EnableTracingMessage {
            get {
                return ResourceManager.GetString("EnableTracingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator Arguments:.
        /// </summary>
        internal static string GeneratorArgsHeader {
            get {
                return ResourceManager.GetString("GeneratorArgsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the generator. Check available generators below..
        /// </summary>
        internal static string GeneratorArgumentDesc {
            get {
                return ResourceManager.GetString("GeneratorArgumentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator Options:.
        /// </summary>
        internal static string GeneratorOptionsHeader {
            get {
                return ResourceManager.GetString("GeneratorOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaffolding failed..
        /// </summary>
        internal static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a Valid MSBuild project file..
        /// </summary>
        internal static string InvalidMsBuildProjectFile {
            get {
                return ResourceManager.GetString("InvalidMsBuildProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code generator found with the name &apos;{0}&apos;..
        /// </summary>
        internal static string NoCodeGeneratorFound {
            get {
                return ResourceManager.GetString("NoCodeGeneratorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No codegenerators are available in this project. Please add &apos;Microsoft.VisualStudio.Web.CodeGeneration.Design&apos; NuGet package to the project..
        /// </summary>
        internal static string NoCodeGeneratorsFound {
            get {
                return ResourceManager.GetString("NoCodeGeneratorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a compatible framework to execute..
        /// </summary>
        internal static string NoCompatibleFrameworks {
            get {
                return ResourceManager.GetString("NoCompatibleFrameworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get ProjectInformation..
        /// </summary>
        internal static string ProjectInformationError {
            get {
                return ResourceManager.GetString("ProjectInformationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to .csproj file in the project..
        /// </summary>
        internal static string ProjectPathOptionDesc {
            get {
                return ResourceManager.GetString("ProjectPathOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Code Generator: {0}.
        /// </summary>
        internal static string SelectedCodeGeneratorStr {
            get {
                return ResourceManager.GetString("SelectedCodeGeneratorStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether to persist any file changes..
        /// </summary>
        internal static string SimulationModeOptionDesc {
            get {
                return ResourceManager.GetString("SimulationModeOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Framework to use. (Short folder name of the tfm. eg. net46).
        /// </summary>
        internal static string TargetFrameworkOptionDesc {
            get {
                return ResourceManager.GetString("TargetFrameworkOptionDesc", resourceCulture);
            }
        }
    }
}
