//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Web.CodeGeneration.Core {
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.Web.CodeGeneration.Core.MessageStrings", typeof(MessageStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding dependency &apos;{0}&apos; version &apos;{1}&apos;..
        /// </summary>
        internal static string AddDependency {
            get {
                return ResourceManager.GetString("AddDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the code generator instance: {0}\r\n{1}.
        /// </summary>
        internal static string CodeGeneratorInstanceCreationError {
            get {
                return ResourceManager.GetString("CodeGeneratorInstanceCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code generators found with the name &apos;{0}&apos;.
        /// </summary>
        internal static string CodeGeneratorNotFound {
            get {
                return ResourceManager.GetString("CodeGeneratorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory is not empty : &apos;{0}&apos;.
        /// </summary>
        internal static string DirectoryNotEmpty {
            get {
                return ResourceManager.GetString("DirectoryNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find dotnet.exe on path. .
        /// </summary>
        internal static string DnuNotFound {
            get {
                return ResourceManager.GetString("DnuNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error running &apos;dotnet restore&apos; : &apos;{0}&apos;.
        /// </summary>
        internal static string DotNetRestoreError {
            get {
                return ResourceManager.GetString("DotNetRestoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided file &apos;{0}&apos; does not exist. This method expects a fully qualified path of an existing file..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file matching the name {0} was not found within any of the folders: {1}.
        /// </summary>
        internal static string FileNotFoundInFolders {
            get {
                return ResourceManager.GetString("FileNotFoundInFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} method with a model parameter is not found in class: {1}.
        /// </summary>
        internal static string MethodNotFound {
            get {
                return ResourceManager.GetString("MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error attempting to create an instace of model for GenerateCode method: {0}.
        /// </summary>
        internal static string ModelCreationFailed {
            get {
                return ResourceManager.GetString("ModelCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple code generators found matching the name &apos;{0}&apos;.
        /// </summary>
        internal static string MultipleCodeGeneratorsFound {
            get {
                return ResourceManager.GetString("MultipleCodeGeneratorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple files with name {0} found within {1}.
        /// </summary>
        internal static string MultipleFilesFound {
            get {
                return ResourceManager.GetString("MultipleFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple {0} methods with a model parameter are found in class: {1}.
        /// </summary>
        internal static string MultipleMethodsFound {
            get {
                return ResourceManager.GetString("MultipleMethodsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; cannot be null or empty..
        /// </summary>
        internal static string NullParamError {
            get {
                return ResourceManager.GetString("NullParamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a part of the path &apos;{0}&apos;.
        /// </summary>
        internal static string PathNotFound {
            get {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file {0} not found within search paths {1}.
        /// </summary>
        internal static string TemplateFileNotFound {
            get {
                return ResourceManager.GetString("TemplateFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error running the template {0}: {1}.
        /// </summary>
        internal static string TemplateProcessingError {
            get {
                return ResourceManager.GetString("TemplateProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to run restore..
        /// </summary>
        internal static string UnableToRunRestore {
            get {
                return ResourceManager.GetString("UnableToRunRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type of library information for template folders.
        /// </summary>
        internal static string UnexpectedTypeLibraryForTemplates {
            get {
                return ResourceManager.GetString("UnexpectedTypeLibraryForTemplates", resourceCulture);
            }
        }
    }
}
