// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.DotNet.Tools.Scaffold.AspNet.Templates.Identity.Pages.Account
{
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RegisterModel : RegisterModelBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassNamespace));
            this.Write(";\r\n\r\nnamespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.IdentityNamespace));
            this.Write(".Pages.Account;\r\n\r\npublic class RegisterModel : PageModel\r\n{\r\n    private readonl" +
                    "y SignInManager<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write("> _signInManager;\r\n    private readonly UserManager<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write("> _userManager;\r\n    private readonly IUserStore<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write("> _userStore;\r\n    private readonly IUserEmailStore<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write("> _emailStore;\r\n    private readonly ILogger<RegisterModel> _logger;\r\n    private" +
                    " readonly IEmailSender _emailSender;\r\n\r\n    public RegisterModel(\r\n        UserM" +
                    "anager<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write("> userManager,\r\n        IUserStore<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write("> userStore,\r\n        SignInManager<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write("> signInManager,\r\n        ILogger<RegisterModel> logger,\r\n        IEmailSender em" +
                    "ailSender)\r\n    {\r\n        _userManager = userManager;\r\n        _userStore = use" +
                    "rStore;\r\n        _emailStore = GetEmailStore();\r\n        _signInManager = signIn" +
                    "Manager;\r\n        _logger = logger;\r\n        _emailSender = emailSender;\r\n    }\r" +
                    "\n\r\n    /// <summary>\r\n    ///     This API supports the ASP.NET Core Identity de" +
                    "fault UI infrastructure and is not intended to be used\r\n    ///     directly fro" +
                    "m your code. This API may change or be removed in future releases.\r\n    /// </su" +
                    "mmary>\r\n    [BindProperty]\r\n    public InputModel Input { get; set; } = default!" +
                    ";\r\n\r\n    /// <summary>\r\n    ///     This API supports the ASP.NET Core Identity " +
                    "default UI infrastructure and is not intended to be used\r\n    ///     directly f" +
                    "rom your code. This API may change or be removed in future releases.\r\n    /// </" +
                    "summary>\r\n    public string? ReturnUrl { get; set; }\r\n\r\n    /// <summary>\r\n    /" +
                    "//     This API supports the ASP.NET Core Identity default UI infrastructure and" +
                    " is not intended to be used\r\n    ///     directly from your code. This API may c" +
                    "hange or be removed in future releases.\r\n    /// </summary>\r\n    public IList<Au" +
                    "thenticationScheme>? ExternalLogins { get; set; }\r\n\r\n    /// <summary>\r\n    /// " +
                    "    This API supports the ASP.NET Core Identity default UI infrastructure and is" +
                    " not intended to be used\r\n    ///     directly from your code. This API may chan" +
                    "ge or be removed in future releases.\r\n    /// </summary>\r\n    public class Input" +
                    "Model\r\n    {\r\n        /// <summary>\r\n        ///     This API supports the ASP.N" +
                    "ET Core Identity default UI infrastructure and is not intended to be used\r\n     " +
                    "   ///     directly from your code. This API may change or be removed in future " +
                    "releases.\r\n        /// </summary>\r\n        [Required]\r\n        [EmailAddress]\r\n " +
                    "       [Display(Name = \"Email\")]\r\n        public string Email { get; set; } = de" +
                    "fault!;\r\n\r\n        /// <summary>\r\n        ///     This API supports the ASP.NET " +
                    "Core Identity default UI infrastructure and is not intended to be used\r\n        " +
                    "///     directly from your code. This API may change or be removed in future rel" +
                    "eases.\r\n        /// </summary>\r\n        [Required]\r\n        [StringLength(100, E" +
                    "rrorMessage = \"The {0} must be at least {2} and at max {1} characters long.\", Mi" +
                    "nimumLength = 6)]\r\n        [DataType(DataType.Password)]\r\n        [Display(Name " +
                    "= \"Password\")]\r\n        public string Password { get; set; } = default!;\r\n\r\n    " +
                    "    /// <summary>\r\n        ///     This API supports the ASP.NET Core Identity d" +
                    "efault UI infrastructure and is not intended to be used\r\n        ///     directl" +
                    "y from your code. This API may change or be removed in future releases.\r\n       " +
                    " /// </summary>\r\n        [DataType(DataType.Password)]\r\n        [Display(Name = " +
                    "\"Confirm password\")]\r\n        [Compare(\"Password\", ErrorMessage = \"The password " +
                    "and confirmation password do not match.\")]\r\n        public string? ConfirmPasswo" +
                    "rd { get; set; }\r\n    }\r\n\r\n\r\n    public async Task OnGetAsync(string? returnUrl " +
                    "= null)\r\n    {\r\n        ReturnUrl = returnUrl;\r\n        ExternalLogins = (await " +
                    "_signInManager.GetExternalAuthenticationSchemesAsync()).ToList();\r\n    }\r\n\r\n    " +
                    "public async Task<IActionResult> OnPostAsync(string? returnUrl = null)\r\n    {\r\n " +
                    "       returnUrl ??= Url.Content(\"~/\");\r\n        ExternalLogins = (await _signIn" +
                    "Manager.GetExternalAuthenticationSchemesAsync()).ToList();\r\n        if (ModelSta" +
                    "te.IsValid)\r\n        {\r\n            var user = CreateUser();\r\n\r\n            awai" +
                    "t _userStore.SetUserNameAsync(user, Input.Email, CancellationToken.None);\r\n     " +
                    "       await _emailStore.SetEmailAsync(user, Input.Email, CancellationToken.None" +
                    ");\r\n            var result = await _userManager.CreateAsync(user, Input.Password" +
                    ");\r\n\r\n            if (result.Succeeded)\r\n            {\r\n                _logger." +
                    "LogInformation(\"User created a new account with password.\");\r\n\r\n                " +
                    "var userId = await _userManager.GetUserIdAsync(user);\r\n                var code " +
                    "= await _userManager.GenerateEmailConfirmationTokenAsync(user);\r\n               " +
                    " code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));\r\n            " +
                    "    var callbackUrl = Url.Page(\r\n                    \"/Account/ConfirmEmail\",\r\n " +
                    "                   pageHandler: null,\r\n                    values: new { area = " +
                    "\"Identity\", userId = userId, code = code, returnUrl = returnUrl },\r\n            " +
                    "        protocol: Request.Scheme)!;\r\n\r\n                await _emailSender.SendEm" +
                    "ailAsync(Input.Email, \"Confirm your email\",\r\n                    $\"Please confir" +
                    "m your account by <a href=\'{HtmlEncoder.Default.Encode(callbackUrl)}\'>clicking h" +
                    "ere</a>.\");\r\n\r\n                if (_userManager.Options.SignIn.RequireConfirmedA" +
                    "ccount)\r\n                {\r\n                    return RedirectToPage(\"RegisterC" +
                    "onfirmation\", new { email = Input.Email, returnUrl = returnUrl });\r\n            " +
                    "    }\r\n                else\r\n                {\r\n                    await _signI" +
                    "nManager.SignInAsync(user, isPersistent: false);\r\n                    return Loc" +
                    "alRedirect(returnUrl);\r\n                }\r\n            }\r\n            foreach (v" +
                    "ar error in result.Errors)\r\n            {\r\n                ModelState.AddModelEr" +
                    "ror(string.Empty, error.Description);\r\n            }\r\n        }\r\n\r\n        // If" +
                    " we got this far, something failed, redisplay form\r\n        return Page();\r\n    " +
                    "}\r\n\r\n    private ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write(" CreateUser()\r\n    {\r\n        try\r\n        {\r\n            return Activator.Create" +
                    "Instance<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write(">();\r\n        }\r\n        catch\r\n        {\r\n            throw new InvalidOperation" +
                    "Exception($\"Can\'t create an instance of \'{nameof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write(")}\'. \" +\r\n                $\"Ensure that \'{nameof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write(")}\' is not an abstract class and has a parameterless constructor, or alternativel" +
                    "y \" +\r\n                $\"override the register page in /Areas/Identity/Pages/Acc" +
                    "ount/Register.cshtml\");\r\n        }\r\n    }\r\n\r\n    private IUserEmailStore<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write("> GetEmailStore()\r\n    {\r\n        if (!_userManager.SupportsUserEmail)\r\n        {" +
                    "\r\n            throw new NotSupportedException(\"The default UI requires a user st" +
                    "ore with email support.\");\r\n        }\r\n        return (IUserEmailStore<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.UserClassName));
            this.Write(">)_userStore;\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        /// <summary>
        /// The current host for the text templating engine
        /// </summary>
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }

private global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel _ModelField;

/// <summary>
/// Access the Model parameter of the template.
/// </summary>
private global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel Model
{
    get
    {
        return this._ModelField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ModelValueAcquired = false;
if (this.Session.ContainsKey("Model"))
{
    this._ModelField = ((global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel)(this.Session["Model"]));
    ModelValueAcquired = true;
}
if ((ModelValueAcquired == false))
{
    string parameterValue = this.Host.ResolveParameterValue("Property", "PropertyDirectiveProcessor", "Model");
    if ((string.IsNullOrEmpty(parameterValue) == false))
    {
        global::System.ComponentModel.TypeConverter tc = global::System.ComponentModel.TypeDescriptor.GetConverter(typeof(global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel));
        if (((tc != null) 
                    && tc.CanConvertFrom(typeof(string))))
        {
            this._ModelField = ((global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel)(tc.ConvertFrom(parameterValue)));
            ModelValueAcquired = true;
        }
        else
        {
            this.Error("The type \'Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel\' of the par" +
                    "ameter \'Model\' did not match the type of the data passed to the template.");
        }
    }
}
if ((ModelValueAcquired == false))
{
    object data = global::Microsoft.DotNet.Scaffolding.TextTemplating.CallContext.LogicalGetData("Model");
    if ((data != null))
    {
        this._ModelField = ((global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel)(data));
    }
}


    }
}


    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class RegisterModelBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
