// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.DotNet.Tools.Scaffold.AspNet.Templates.net11.BlazorIdentity.Pages.Manage
{
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using System;

    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class Passkeys : PasskeysBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("@page \"/Account/Manage/Passkeys\"\r\n\r\n");

if (!string.IsNullOrEmpty(Model.DbContextNamespace))
{

            this.Write("@using ");
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.DbContextNamespace ));
            this.Write("\r\n");
}
            this.Write("@using Microsoft.AspNetCore.Identity\r\n@using System.ComponentModel.DataAnnotation" +
                    "s\r\n@using System.Buffers.Text\r\n\r\n@inject UserManager<");
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.UserClassName ));
            this.Write("> UserManager\r\n@inject SignInManager<");
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.UserClassName ));
            this.Write("> SignInManager\r\n@inject IdentityRedirectManager RedirectManager\r\n\r\n<PageTitle>Ma" +
                    "nage your passkeys</PageTitle>\r\n\r\n<h3>Manage your passkeys</h3>\r\n\r\n<StatusMessag" +
                    "e Message=\"@message\" />\r\n\r\n@if (currentPasskeys is { Count: > 0 })\r\n{\r\n    <tabl" +
                    "e class=\"table\">\r\n        <tbody>\r\n            @foreach (var passkey in currentP" +
                    "asskeys)\r\n            {\r\n                <tr>\r\n                    <td>\r\n       " +
                    "                 <div>@PasskeyAuthenticators.GetDisplayName(passkey)</div>\r\n    " +
                    "                    <small class=\"text-muted\">Created @passkey.CreatedAt.UtcDate" +
                    "Time.ToString(\"MMM d, yyyy\") (UTC)</small>\r\n                    </td>\r\n         " +
                    "           <td>\r\n                        @{\r\n                            var cre" +
                    "dentialId = Base64Url.EncodeToString(passkey.CredentialId);\r\n                   " +
                    "     }\r\n                        <form @formname=\"@($\"update-passkey-{credentialI" +
                    "d}\")\" @onsubmit=\"UpdatePasskey\" method=\"post\">\r\n                            <div" +
                    ">\r\n                                <input type=\"hidden\" name=\"CredentialId\" valu" +
                    "e=\"@credentialId\" />\r\n                                <button type=\"submit\" name" +
                    "=\"Action\" value=\"rename\" class=\"btn btn-primary\" title=\"Rename this passkey\">Ren" +
                    "ame</button>\r\n                                <button type=\"submit\" name=\"Action" +
                    "\" value=\"delete\" class=\"btn btn-danger\" title=\"Remove this passkey from your acc" +
                    "ount\">Delete</button>\r\n                            </div>\r\n                     " +
                    "   </form>\r\n                    </td>\r\n                </tr>\r\n            }\r\n   " +
                    "     </tbody>\r\n    </table>\r\n}\r\nelse\r\n{\r\n    <p>No passkeys are registered.</p>\r" +
                    "\n}\r\n\r\n<form @formname=\"add-passkey\" @onsubmit=\"AddPasskey\" method=\"post\">\r\n    @" +
                    "if (currentPasskeys is { Count: >= MaxPasskeyCount })\r\n    {\r\n        <p class=\"" +
                    "text-danger\">You have reached the maximum number of allowed passkeys. Please del" +
                    "ete one before adding a new one.</p>\r\n    }\r\n    else\r\n    {\r\n        <PasskeySu" +
                    "bmit Operation=\"PasskeyOperation.Create\" Name=\"Input\" class=\"btn btn-primary\">Ad" +
                    "d a new passkey</PasskeySubmit>\r\n    }\r\n\r\n</form>\r\n\r\n@code {\r\n    private const " +
                    "int MaxPasskeyCount = 100;\r\n\r\n    private string? message;\r\n    private ");
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.UserClassName ));
            this.Write("? user;\r\n    private IList<UserPasskeyInfo>? currentPasskeys;\r\n\r\n    [CascadingPa" +
                    "rameter]\r\n    private HttpContext HttpContext { get; set; } = default!;\r\n\r\n    [" +
                    "SupplyParameterFromTempData(Name = IdentityRedirectManager.StatusMessageKey)]\r\n " +
                    "   private string? IdentityStatusMessage { get; set; }\r\n\r\n    [SupplyParameterFr" +
                    "omForm]\r\n    private string? Action { get; set; }\r\n\r\n    [SupplyParameterFromFor" +
                    "m]\r\n    private string? CredentialId { get; set; }\r\n\r\n    [SupplyParameterFromFo" +
                    "rm(FormName = \"add-passkey\")]\r\n    private PasskeyInputModel Input { get; set; }" +
                    " = default!;\r\n\r\n    protected override async Task OnInitializedAsync()\r\n    {\r\n " +
                    "       message = IdentityStatusMessage;\r\n        IdentityStatusMessage = null;\r\n" +
                    "        Input ??= new();\r\n\r\n        user = await UserManager.GetUserAsync(HttpCo" +
                    "ntext.User);\r\n        if (user is null)\r\n        {\r\n            RedirectManager." +
                    "RedirectTo(\"Account/InvalidUser\");\r\n            return;\r\n        }\r\n        curr" +
                    "entPasskeys = await UserManager.GetPasskeysAsync(user);\r\n    }\r\n\r\n    private as" +
                    "ync Task AddPasskey()\r\n    {\r\n        if (user is null)\r\n        {\r\n            " +
                    "RedirectManager.RedirectTo(\"Account/InvalidUser\");\r\n            return;\r\n       " +
                    " }\r\n\r\n        if (!string.IsNullOrEmpty(Input.Error))\r\n        {\r\n            Id" +
                    "entityStatusMessage = $\"Error: {Input.Error}\";\r\n            RedirectManager.Redi" +
                    "rectToCurrentPage();\r\n            return;\r\n        }\r\n\r\n        if (string.IsNul" +
                    "lOrEmpty(Input.CredentialJson))\r\n        {\r\n            IdentityStatusMessage = " +
                    "\"Error: The browser did not provide a passkey.\";\r\n            RedirectManager.Re" +
                    "directToCurrentPage();\r\n            return;\r\n        }\r\n\r\n        if (currentPas" +
                    "skeys!.Count >= MaxPasskeyCount)\r\n        {\r\n            IdentityStatusMessage =" +
                    " \"Error: You have reached the maximum number of allowed passkeys.\";\r\n           " +
                    " RedirectManager.RedirectToCurrentPage();\r\n            return;\r\n        }\r\n\r\n   " +
                    "     var attestationResult = await SignInManager.PerformPasskeyAttestationAsync(" +
                    "Input.CredentialJson);\r\n        if (!attestationResult.Succeeded)\r\n        {\r\n  " +
                    "          IdentityStatusMessage = $\"Error: Could not add the passkey: {attestati" +
                    "onResult.Failure.Message}\";\r\n            RedirectManager.RedirectToCurrentPage()" +
                    ";\r\n            return;\r\n        }\r\n\r\n        // If the authenticator is known, a" +
                    "ssign the inferred name\r\n        if (PasskeyAuthenticators.TryGetDefaultDisplayN" +
                    "ame(attestationResult.Passkey, out var defaultName))\r\n        {\r\n            att" +
                    "estationResult.Passkey.Name = defaultName;\r\n        }\r\n\r\n        var addPasskeyR" +
                    "esult = await UserManager.AddOrUpdatePasskeyAsync(user, attestationResult.Passke" +
                    "y);\r\n        if (!addPasskeyResult.Succeeded)\r\n        {\r\n            IdentitySt" +
                    "atusMessage = \"Error: The passkey could not be added to your account.\";\r\n       " +
                    "     RedirectManager.RedirectToCurrentPage();\r\n            return;\r\n        }\r\n\r" +
                    "\n        // If a name was inferred, go back to the passkeys list\r\n        if (!s" +
                    "tring.IsNullOrEmpty(attestationResult.Passkey.Name))\r\n        {\r\n            Ide" +
                    "ntityStatusMessage = \"Your passkey was added successfully.\";\r\n            Redire" +
                    "ctManager.RedirectToCurrentPage();\r\n            return;\r\n        }\r\n\r\n        //" +
                    " For unknown authenticators, prompt the user to enter a name\r\n        var creden" +
                    "tialIdBase64Url = Base64Url.EncodeToString(attestationResult.Passkey.CredentialI" +
                    "d);\r\n        RedirectManager.RedirectTo($\"Account/Manage/RenamePasskey/{credenti" +
                    "alIdBase64Url}\");\r\n    }\r\n\r\n    private async Task UpdatePasskey()\r\n    {\r\n     " +
                    "   switch (Action)\r\n        {\r\n            case \"rename\":\r\n                Redir" +
                    "ectManager.RedirectTo($\"Account/Manage/RenamePasskey/{CredentialId}\");\r\n        " +
                    "        break;\r\n            case \"delete\":\r\n                await DeletePasskey(" +
                    ");\r\n                break;\r\n            default:\r\n                IdentityStatus" +
                    "Message = $\"Error: Unknown action \'{Action}\'.\";\r\n                RedirectManager" +
                    ".RedirectToCurrentPage();\r\n                break;\r\n        }\r\n    }\r\n\r\n    priva" +
                    "te async Task DeletePasskey()\r\n    {\r\n        if (user is null)\r\n        {\r\n    " +
                    "        RedirectManager.RedirectTo(\"Account/InvalidUser\");\r\n            return;\r" +
                    "\n        }\r\n\r\n        byte[] credentialId;\r\n        try\r\n        {\r\n            " +
                    "credentialId = Base64Url.DecodeFromChars(CredentialId);\r\n        }\r\n        catc" +
                    "h (FormatException)\r\n        {\r\n            IdentityStatusMessage = \"Error: The " +
                    "specified passkey ID had an invalid format.\";\r\n            RedirectManager.Redir" +
                    "ectToCurrentPage();\r\n            return;\r\n        }\r\n\r\n        var result = awai" +
                    "t UserManager.RemovePasskeyAsync(user, credentialId);\r\n        if (!result.Succe" +
                    "eded)\r\n        {\r\n            IdentityStatusMessage = \"Error: The passkey could " +
                    "not be deleted.\";\r\n            RedirectManager.RedirectToCurrentPage();\r\n       " +
                    "     return;\r\n        }\r\n\r\n        IdentityStatusMessage = \"Passkey deleted succ" +
                    "essfully.\";\r\n        RedirectManager.RedirectToCurrentPage();\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }

        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        /// <summary>
        /// The current host for the text templating engine
        /// </summary>
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }

private global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel _ModelField;

/// <summary>
/// Access the Model parameter of the template.
/// </summary>
private global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel Model
{
    get
    {
        return this._ModelField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ModelValueAcquired = false;
if (this.Session.ContainsKey("Model"))
{
    this._ModelField = ((global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel)(this.Session["Model"]));
    ModelValueAcquired = true;
}
if ((ModelValueAcquired == false))
{
    string parameterValue = this.Host.ResolveParameterValue("Property", "PropertyDirectiveProcessor", "Model");
    if ((string.IsNullOrEmpty(parameterValue) == false))
    {
        global::System.ComponentModel.TypeConverter tc = global::System.ComponentModel.TypeDescriptor.GetConverter(typeof(global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel));
        if (((tc != null)
                    && tc.CanConvertFrom(typeof(string))))
        {
            this._ModelField = ((global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel)(tc.ConvertFrom(parameterValue)));
            ModelValueAcquired = true;
        }
        else
        {
            this.Error("The type \'Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel\' of the par" +
                    "ameter \'Model\' did not match the type of the data passed to the template.");
        }
    }
}
if ((ModelValueAcquired == false))
{
    object data = global::Microsoft.DotNet.Scaffolding.TextTemplating.CallContext.LogicalGetData("Model");
    if ((data != null))
    {
        this._ModelField = ((global::Microsoft.DotNet.Tools.Scaffold.AspNet.Models.IdentityModel)(data));
    }
}


    }
}


    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class PasskeysBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0)
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}